export const moralQuestions = [
  "får man kissa på sig hos nån annan",
  "får man snatta från en butik om man stått i kö i 20 min och ingen kommit till kassan",
  "får man sälja sex för pengar",
  "får man bjuda en vegan på ickevegansk mat om det inte märks och man slipper omständligheter? typ du råkade baka en paj med smör istället för margarin",
  "får man ha kvar tinder om man har flickvän men inte använder det",
  "får man sova över hos en kompis av motsatt kön om man har förhållande",
  "får man sova hos sin gamla kk för att man är arg på sin partner",
  "får man flirta för att få gratis drinkar om man har en partner",
  "får man ligga med sitt ex bästa kompis",
  "får man ligga med sin kompis ex",
  "får man kräva en vän på pengar om den förstört något hemma hos en",
  "får man lämna sin kompis om hon är jättefull och man vet att det kommer gå fel men kompisen går alltid fel så egentligen kan man inte rädda det",
  "får man lead någon on till att tro att det kan bli ett förhållande när man vet att man inte vill ha nåt seriöst",
  "får man ligga med nån annan när man har en uttalad kk",
  "får man knarka och ljuga om det för sin partner",
  "får man dejta flera samtidigt",
  "är ljuga och inte berätta sanningen samma sak?",
  "får man köra på en människa och flya om ingen ser men man vet att om man stannar och anmäler kommer man få minst 20 års fängelse",
  "får man sno från en rik om man vet att de har försäkring",
  "får man ha kompisar av motsatt kön om man har en partner",
  "får man umgås med folk man legat med om har en ny partner",
  "måste man berätta för sin partner att man legat med folk man umgås med",
  "får man kyssa någon om man har herpesutbrott (utan att säga innan)",
  "får man snegla i nåns telefon när de smsar om man sitter bredvid",
  "får man gå igenom någon telefon om man kan koden och misstänker något",
  "får man dejta sin bästis syter/bror",
  "får man skcika tillbaka maten för att man själv tycker den är äcklig även om det inte är något fel på tillagningen",
  "får man säga att vinet är dåligt om man inte gillar det vid ett provsmak",
  "får man planka på en spårvagn",
  "ringer man polisen om ens kompis kört rattfull?",
  "får man ligga i ens kompis lägenhet när kompisen är däR",
  "får man ligga i ens kompis lägenhet",
  "får man ta någons oskuld om de är fulla och man själv är nykter",
  "får man ligga med någon random när man ör nykter men de ör fulla",
  "Hur många örnar får plats på DIN krabba???",
  "får man stalka sitt ex",
  "får man ragga upp sitt ex kompisar",
  "får man säga att man är gravid trotsd att man inte är det men killen behöver skräpa sig",
  "hur många får man ligga med",
  "får man ljuga om hur många man legat med för att verka bättre",
  "får man ligga med nån som är 10 år yngre",
  "får man ligga med en 17-åring om man är superkär",
  "får man call one out för att de inte har adhd när de säger att de har adhd men man tror verkligen inte att de har adhd",
  "får man neka en kompis sovplats när de behöver men man vill vara själv",
  "kan man ligga med en kompis och sen förbli kompisar",
  "får man ligga med någon när man är i en maktposition",
  "får man dricka i en alkoholists sällskap",
  "du är sjukd och döende, träffar en man på en buss osm säger att han kan göra dig frisk om en person i sverige dör, går du med på det",
  "du är fattig och träffar en man som säger att han ger dig en miljon om du klickar på knappen, men då dör någon",
  "ditt barn dör eller 10k chilenare dör, vad väljer du",
  "om din kompis alltid super ut sig, måste du alltid ta hand om personen när den behöver det",
  "ni är på semester i ett annat land och din kjompis vill gå hem med en random, tillåter du?",
  "en person med icke-vit bakgrund går bakom dig in i porten, du har aldrig sett personen innan, den kan bo i området men du vet inte säker och är ocäker på om det verkar rasistiskt om du säger till, säger du till eller inte?",
  "du har lovat en kompis sovplats men hittar ett 8/10 ragg på klubben, är det ok att smita och lämna kompisen?",
  "måste man källsortera?",
  "får man skälla ut någon annans unge?",
  "antingen får du o din bästis varsin Peugot eller så får du en Audi R8 pch din kompis får ingenting",
  "måste man lämna sin barndomskompis om den visar sig va homofob/rasist men ändå är skön i övrigt",
  "får man rösta SD",
  "får man sluta va vän med någon för att man inte röstar likadant i valet",
  "får man skriva sig i ett annat land för att betala mindre skatt",
  "måste man alltid swisha om någon bjuder en på öl?",
  "får man va smyg-taskig mot någon på jobbet så att de inte trivs och själva säger upp sig?",
  "om ens kompis verkar ha en ätstörning, måste man ta upp det?",
  "får man ligga med en kollega?",
  "är det ok med reglerat surrogatmödraskap?",
  "är verkligen systembolaget så jävla bra?",
  "bör man införa ett lagligt tredje kön?",
];
