export const neverHaveIEverQuestions = [
  "...fått sparken",
  "...tagit droger",
  "...ghostat någon",
  "...kissat på mig i vuxen ålder",
  "...legat med någon i rummet",
  "...bajsat på mig i vuxen ålder",
  "...bokat hotellrum för natt med kärlek",
  "...hånglat med nån i rummet",
  "...legat när fler varit i samma rum",
  "...rökt weed",
  "...varit i fyllecell",
  "...tagit en medveten springnota",
  "...tatuerat mig på fyllan",
  "...ångrat ett ligg",
  "...kört bil med alkohol i kroppen",
  "...wingat turbo med 100% garanti",
  "...somnat i ett möte",
  "...legat på offentlig plats",
  "...blivit utslängd från nattklubb",
  "...hånglat med tre eller fler på samma kväll",
  "...varit på rave",
  "...sagt att jag aldrig kommer dricka igen",
  "...somnat under sex",
  "...eldat ett bord",
  "...spelat lökgolf",
  "...legat med mitt ex bästa kompis",
  "...haft en trekant",
  "...legat på en toa",
  "...spytt i någon annans säng",
  "...onanerat på jobbet",
  "...sjukanmält mig för att jag varit bakis",
  "...stalkat mitt ex",
  "...haft en könssjukdom",
  "...kysst någon jag tyckt var ful",
  "...supit varje dag under en vecka",
  "...kysst en väns förälder",
  "...raggat upp nån kvart i tre som verkligen kunde varit vem som helst",
  "...köpt bärs i tyskland",
  "...blivit nekad inträde till en riktigt sunkig pub (andra lång)",
  "...varit på strippklubb",
  "...strippat",
  "...sålt feet pics",
  "...ljugit om vilket parti jag röstar på",
];
