export const peklekenData = [
  "vem knarkar mest",
  "vem har legat med flest",
  "vem får snyggast ragg",
  "vem är snyggast",
  "vem har störst chans att komma med i PH",
  "vem har störst chans att va med i Draknästet",
  "vem är roligast",
  "vem är tråkigast",
  "vem kommer skilja sig",
  "vem kommer gifta sig först",
  "vem kommer få barn först",
  "vem kommer bli statsminister",
  "vem kommer få sparken först",
  "vem är troligast att bli alkis",
  "vem blir miljonär",
  "vem är närmast att vara oskuld",
  "vem super mest",
  "vem har mörkast hemligheter",
  "vem har flest könssjukdomar",
  "vem kommer dö först",
  "vem är bäst i sängen",
  "vem behöver gå på ett AA-möte",
  "vem är mest kinky",
  "vem har skickat flest nudes",
  "vem är mest trolig att hamna i fängelse",
  "vem är mest händig",
  "vem är mest pryd",
  "vem är alltid sen",
  "vem flirtar mest",
  "vem onanerar oftast",
  "vem kommer få ölmage först",
  "vem gråter mest",
  "vem tål mest alkohol",
  "vem är girigast",
  "vem har haft flest förhållanden",
  "vem hatar sitt liv mest",
  "vem är mest svenne",
  "vem har blivit uppraggad flest gånger",
  "vem ser äldst ut",
  "vem border dricka mer",
  "vem skulle du inte låna ut din bil till",
  "vem kommer bli uppraggad ikväll",
  "vem raggar sämst",
  "vem är mest allmänbildad",
  "vem brukar bli fullast",
  "vem är mest desperat",
  "vem har blivit utkastad flest gånger från krogen",
  "vem har snyggast rumpa",
  "vem är mest bortskämd",
  "vem har bäst självförtroende",
  "vem har haft sex på konstigast ställen",
  "vem skulle betala för sex",
  "vem har gjort det roligaste på fyllan",
  "vem av oss kommer inte komma ihåg denhär kvällen imorgon",
  "vem skulle kunna delta i en porrfilm",
  "vem kollar mest porr",
  "vem tar flest selfies",
  "vem är största snitchen",
  "vem är största drinkludret",
  "vem har flest tatueringar",
  "vem är mest wifey material",
  "vem har störst skulder",
  "vem kommer bli snyggast som gammal",
  "vem äter ute mest",
  "vem är lättast att få i sängen",
  "vem har sämst karma",
  "vem skulle du vilja gå på dejt med",
  "vem dumpade någon senast",
  "vem skulle kunna dejta två samtidigt",
];
